language: node_js
node_js: 6
branches:
  except:
  - gh-pages
env:
  global:
  - SOURCE_DIR="docs"
  - GIT_NAME="RWEDA Bot"
  - GIT_EMAIL="rwedabot@redwoodeda.com"

script:
- npm test
- npm run docs
- "$(npm bin)/gh-pages-travis"

before_install:
- openssl aes-256-cbc -K $encrypted_8c5e3c7b342d_key -iv $encrypted_8c5e3c7b342d_iv
  -in id_rsa.enc -out id_rsa -d
